# CSCI_4230_PL_11_26_2018.md

* Default parameters - are given a value to use if the corresponding argument is not provided 
* Named parameters - can be provided as arguments in any order, but must be accompanied by a name

Ada putting

```ada
put(item=>37, base=>8)
put(base=>8, item=>37)
put(37, base=>8)
```

Python printing with default args.

```python
print("Hello") # print and go to newline
print("Hello", end="") # print w/out going to a newline
```

* __Variable arguments__ allows an unlimited number of arguments

C's printf function

```c
printf("There are %d ways to go", 45)
```

## Return values

* functional languages return the value that the body of the subroutine evaluates to.
* Imperative langs have an explicit return statement
* The ML family and several scripting languages allow a subroutine to return multiple values.

* An __expectation__ is an unexpected or unusual condition that arises during the execution of a program
* First approved in PL/I (PL 1), now supported by most programming languages
* May be detected automatically
  * Java is notoriously
* OR explicitly thrown by the program
  * no legal value to return
* Must be __caught__ or handled by another part of the program

Without exception handling, there are 3 options

1. To produce a value that is essentially a sentinel value
2. Return a status value along with the return value that indicate wether or not there was an error
3. Take a closure as additional parameter that represents an error handling routine
    1. "Failure Continuation"

C++ example of try-catch

```c++
try{
  if (something_unexpected) 
    throw my_error("oops!");
} catch (my_error e) {
  cout << e.explanation << endl;
}
```

in practice you would never want to trigger an exeception in a try-block

BUT if an exception is thrown then jump immediately to the `catch`

## Exception handlers

1. Recover from an exception and continue executing the program
2. Clean up any resources allocated in the local block, then pass back to calling (the subr that called me) function and let that handle it.
3. If recovery is not possible, display error message (A CLEAR AND USEFUL ONE) and terminate the program

Erlang incorporates fauly tolerance into the language

C++ example of exception

```c++
class duplicate_in_set {
  public:
    item dup; // element that was inserted twice

    duplicate_in_set(item d) : dup (d) { }
};
```

C++ example of calling such an exception

```c++
throw duplicate_in_set(d);
```

## Coroutines

A __coroutine__ is a closuree that can be jumped to by a __transfer__ operation

* When a tranfer happens we have to save the old program counter is saved
* The coroutine starts whereever the program originally left it.
* Different from a continuation, which always refers to the same location and context every time its activated
* Each coroutine must have it's own call stack
* A coroutine is represented using a structure called a context block

## Transfer

1. Pushes all the important register values that need to be saved, including the return address onto the current stack
2. Change the stack pointer to now point to the new stack.
    1. We have info on where this stack is from the context block
3. Pop the return address and any other saved registers from the new stack and return to that address
